pipeline:
  publish:
    image: plugins/docker
    repo: quay.io/honestbee/drone-quay-demo
    registry: quay.io
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - master
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
      - DOCKER_REGISTRY
      - DOCKER_REPO
