services:
  webserver:
    image: quay.io/honestbee/drone-quay-demo

pipeline:
  publish:
    image: plugins/docker
    repo: quay.io/honestbee/drone-quay-demo
    registry: quay.io
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - master
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
      - DOCKER_REGISTRY
      - DOCKER_REPO

  test-curl:
    image: quay.io/joerx/mt
    pull: true
    commands:
      curl http://webserver:3000
    when:
      branch:
        - master
